### ISSUE TITLE
[xFME Road Map] Finish FPS Controller

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [FriskTheFallenHuman/xFrame-Work-SubEngine#2]
Has the latest commit 23677f3ca6be8a2196e07202bbd5a5acf89822bd we added a basic FPS controller though it is very basic so far the current this needs to be finished to move on to our next goal:

- [ ] Proper player pickup system.
- [ ] Implement Fall Damage.
- [ ] Make the player actually die and had a Game Over screen.
- [ ] Jumping sounds/Crouch sounds.
- [ ] Player crippling system (stamina reduce if our legs are broken or we are low of health)
- [ ] Hit box base damage system.
