### ISSUE TITLE
[xFME Road Map] Third person mode

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [FriskTheFallenHuman/xFrame-Work-SubEngine#3]
in our issue #2 we mentioned about stuffs like Hit box base damage system in order to achieve them we need to implement a Third person mode in our `PlayerController.cs` to do so we need to follow:

- [ ] Third person camera.
- [ ] Third person <> First person camera switch.
- [ ] Player model with animation and animation states.
- [ ] Ragdoll on dead or on falling.
- [ ] Animation based footsteps instead of the current ( Moving )
- [ ] Proper viewbob for both modes
