### ISSUE TITLE
[xFME Road Map] Interface

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [FriskTheFallenHuman/xFrame-Work-SubEngine#4]
Currently our only form of interface is our basic Hud (`PlayerHUD.cs`) that it just display basic information, no In Game/Main Menu for our basic menu we need:

- [ ] Main Menu: New Game/Load Game/Settings/Credits and Exit,
- [ ] A version label for the current version and disclaimer about the current state of the engine.
- [ ] In Game Menu: Resume Game/Save Game/Load Game/Settings/Exit To Main Menu and Quit.
- [ ] Settings Panel: Had all of the Graphical Settings/Keyboard Layout and Sound options that you can find in the project settings.
- [ ] Saving/Loading of the settings in a .json file.
- [ ] Saving/Loading of the game saves.
