### ISSUE TITLE
[xFME Road Map] Game Manager

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [FriskTheFallenHuman/xFrame-Work-SubEngine#5]
In order to make game be a **game**  we need a `GameManager` that could handle:

- [ ] Save/Loading  this is connected with issue #4 check marks 5 and 6.
- [ ] Game Flags/Quest Complete/Enemies Killed etc.
- [ ] Game states using Enums `STATE_ACTIVE, STATE_DEFEAT, STATE_DEAD ` etc.
- [ ] Audio Control (Ambient sounds, UI Sounds, etc)
- [ ] Video Control (Resolution, Quality Control etc)
